version: "3.9"

services:
  app:
    build: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080

      # Postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: foodservice_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass

      # Rabbit
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: admin
      RABBIT_PASSWORD: admin
      RABBIT_VHOST: "foodservice"

    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network


  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: foodservice_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    ports:
      - "5432:5432"
    volumes:
      # Хранение данных
      - postgres_data:/var/lib/postgresql/data
      # Автоинициализация — запускается ТОЛЬКО если volume пустой
      - ./deployment/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d foodservice_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network


  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: "/"

      # Ключевое! Автозагрузка конфигурации:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - ./deployment/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    restart: unless-stopped
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

  user_generator:
    build:
      context: .
      dockerfile: Dockerfile.generator
    container_name: user_generator
    depends_on:
      app:
        condition: service_started
    environment:
      # Параметры генерации:
      # -count 10 = генерировать 10 пользователей
      # -interval 5s = интервал между каждым пользователем
      # Убрать -count для непрерывной генерации
    command: ["/bin/user_generator", "-count", "20", "-interval", "3s", "-url", "http://app:8080"]
    networks:
      - app-network
    restart: "no"

volumes:
  postgres_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
