// Code generated by MockGen. DO NOT EDIT.
// Source: internal/worker_service/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/worker_service/repository.go -destination=internal/worker_service/mock/repository_mock.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	"2248_FoodDeliveryService/internal/models"
	"context"
	reflect "reflect"

	"github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

func (m *MockRepository) CreateOrder(ctx context.Context, userID string) (uuid.UUID, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) ChangeOrderStatus(ctx context.Context, newStatusData *models.ChangeOrderStatusData) error {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) GetOrdersForUser(ctx context.Context, userID string, isActive bool) ([]*models.OrderInfo, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) PublishNewOrder(orderId string) error {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) StartStatusChangeConsumer(queueName string) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) GetUserByLogin(ctx context.Context, login string) (*models.UserData, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) RegisterUser(ctx context.Context, login, password string) (*models.UserData, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) CreateUser(ctx context.Context, user *models.UserData) (*models.UserData, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) UpdateUser(ctx context.Context, user *models.UserData) (*models.UserData, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) DeleteUser(ctx context.Context, userID string) error {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) GetUserByID(ctx context.Context, userID string) (*models.UserData, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) CreateSession(ctx context.Context, sessionID, userID string) error {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) GetSessionByUserID(ctx context.Context, userID string) (*models.Session, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockRepository) UpdateSessionExpiry(ctx context.Context, sessionID string) error {
	//TODO implement me
	panic("implement me")
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// PublishOrderStatus mocks base method.
func (m *MockRepository) PublishOrderStatus(orderID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderStatus", orderID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderStatus indicates an expected call of PublishOrderStatus.
func (mr *MockRepositoryMockRecorder) PublishOrderStatus(orderID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderStatus", reflect.TypeOf((*MockRepository)(nil).PublishOrderStatus), orderID, status)
}

// StartNewOrdersConsumer mocks base method.
func (m *MockRepository) StartNewOrdersConsumer(queueName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartNewOrdersConsumer", queueName)
}

// StartNewOrdersConsumer indicates an expected call of StartNewOrdersConsumer.
func (mr *MockRepositoryMockRecorder) StartNewOrdersConsumer(queueName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartNewOrdersConsumer", reflect.TypeOf((*MockRepository)(nil).StartNewOrdersConsumer), queueName)
}
